import React, { createContext, useContext } from "react";
import { useApolloClient } from "@apollo/client";
import {
  useOnGroupCreatedSubscription,
  useOnGroupUpdatedSubscription,
  GroupBasicInfoFragmentDoc, // Generated by codegen
} from "../graphql"; // Adjust path to your codegen output
import { useNotifications } from "../providers/NotificationProvider";

interface GroupSubscriptionContextType {}

const GroupSubscriptionContext = createContext<
  GroupSubscriptionContextType | undefined
>(undefined);

export const GroupSubscriptionProvider: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  const client = useApolloClient();
  const { addNotification } = useNotifications();

  // 1. Subscription for NEW Groups
  useOnGroupCreatedSubscription({
    onData: ({ data }) => {
      const createdGroup = data.data?.groupCreated;
      if (!createdGroup) return;

      // addNotification({
      //   id: crypto.randomUUID(),
      //   title: "Group",
      //   message: `${createdGroup.name || "Group"} created`,
      //   createdAt: new Date(),
      //   read: false,
      // });

      client.cache.writeFragment({
        id: client.cache.identify({
          __typename: "Group",
          id: createdGroup.id,
        }),
        fragment: GroupBasicInfoFragmentDoc,
        fragmentName: "GroupBasicInfo",
        data: createdGroup,
      });

      client.cache.modify({
        fields: {
          groupsTable(
            existing = { totalCount: 0, edges: [] },
            { toReference, readField }
          ) {
            const newRef = toReference(
              { __typename: "Group", id: createdGroup.id },
              true
            );
            if (!newRef) return existing;

            const alreadyExists = existing.edges?.some(
              (edge: any) => readField("id", edge.node) === createdGroup.id
            );
            if (alreadyExists) return existing;

            const result = {
              ...existing,
              totalCount: (existing.totalCount ?? 0) + 1,
              edges: [
                { __typename: "GroupEdge", node: newRef },
                ...(existing.edges ?? []),
              ],
            };

            console.log("✅ NEW result:", result); // <-- هل يظهر بـ 11 edge دلوقتي؟
            return result;
          },
        },
      });
    },
    onError: (err) => console.error("OnGroupCreated Subscription Error:", err),
  });
  // 2. Subscription for UPDATED Groups
  useOnGroupUpdatedSubscription({
    onData: ({ data }) => {
      const updatedGroup = data.data?.groupUpdated;
      if (!updatedGroup?.id) return;

      // addNotification({
      //   id: crypto.randomUUID(),
      //   title: "Group",
      //   message: `Group details updated`,
      //   createdAt: new Date(),
      //   read: false,
      // });

      // Write directly to cache — Apollo automatically re-renders any component viewing this Group ID
      client.cache.writeFragment({
        id: client.cache.identify({
          __typename: "Group",
          id: updatedGroup.id,
        }),
        fragment: GroupBasicInfoFragmentDoc,
        fragmentName: "GroupBasicInfo",
        data: updatedGroup,
      });
    },
    onError: (err) => console.error("OnGroupUpdated Subscription Error:", err),
  });

  return (
    <GroupSubscriptionContext.Provider value={{}}>
      {children}
    </GroupSubscriptionContext.Provider>
  );
};

export const useGroupSubscription = () => {
  const context = useContext(GroupSubscriptionContext);
  if (!context) {
    throw new Error(
      "useGroupSubscription must be used within a GroupSubscriptionProvider"
    );
  }
  return context;
};
