// list for surahs in the Quran with their corresponding numbers and names in Arabic and English
export const surahs = [
  {
    totalCount: 7,
    number: 1,
    name: "Al-Fatiha",
    name_ar: "الفاتحة",
  },
  {
    totalCount: 286,
    number: 2,
    name: "Al-Baqarah",
    name_ar: "البقرة",
  },
  { totalCount: 200, number: 3, name: "Al-Imran", name_ar: "آل عمران" },
  { totalCount: 176, number: 4, name: "An-Nisa", name_ar: "النساء" },
  { totalCount: 120, number: 5, name: "Al-Ma'idah", name_ar: "المائدة" },
  { totalCount: 165, number: 6, name: "Al-An'am", name_ar: "الأنعام" },
  { totalCount: 206, number: 7, name: "Al-A'raf", name_ar: "الأعراف" },
  { totalCount: 75, number: 8, name: "Al-Anfal", name_ar: "الأنفال" },
  { totalCount: 129, number: 9, name: "At-Tawbah", name_ar: "التوبة" },
  { totalCount: 109, number: 10, name: "Yunus", name_ar: "يونس" },
  { totalCount: 123, number: 11, name: "Hud", name_ar: "هود" },
  { totalCount: 111, number: 12, name: "Yusuf", name_ar: "يوسف" },
  { totalCount: 43, number: 13, name: "Ar-Ra'd", name_ar: "الرعد" },
  { totalCount: 52, number: 14, name: "Ibrahim", name_ar: "إبراهيم" },
  { totalCount: 99, number: 15, name: "Al-Hijr", name_ar: "الحجر" },
  { totalCount: 128, number: 16, name: "An-Nahl", name_ar: "النحل" },
  { totalCount: 111, number: 17, name: "Al-Isra", name_ar: "الإسراء" },
  { totalCount: 110, number: 18, name: "Al-Kahf", name_ar: "الكهف" },
  { totalCount: 98, number: 19, name: "Maryam", name_ar: "مريم" },
  { totalCount: 135, number: 20, name: "Ta-Ha", name_ar: "طه" },
  { totalCount: 112, number: 21, name: "Al-Anbiya", name_ar: "الأنبياء" },
  { totalCount: 78, number: 22, name: "Al-Hajj", name_ar: "الحج" },
  { totalCount: 118, number: 23, name: "Al-Mu'minun", name_ar: "المؤمنون" },
  { totalCount: 64, number: 24, name: "An-Nur", name_ar: "النور" },
  { totalCount: 77, number: 25, name: "Al-Furqan", name_ar: "الفرقان" },
  { totalCount: 227, number: 26, name: "Ash-Shu'ara", name_ar: "الشعراء" },
  { totalCount: 93, number: 27, name: "An-Naml", name_ar: "النمل" },
  { totalCount: 88, number: 28, name: "Al-Qasas", name_ar: "القصص" },
  { totalCount: 69, number: 29, name: "Al-Ankabut", name_ar: "العنكبوت" },
  { totalCount: 60, number: 30, name: "Ar-Rum", name_ar: "الروم" },
  { totalCount: 34, number: 31, name: "Luqman", name_ar: "لقمان" },
  { totalCount: 30, number: 32, name: "As-Sajdah", name_ar: "السجدة" },
  { totalCount: 73, number: 33, name: "Al-Ahzab", name_ar: "الأحزاب" },
  { totalCount: 54, number: 34, name: "Saba", name_ar: "سبأ" },
  { totalCount: 45, number: 35, name: "Fatir", name_ar: "فاطر" },
  { totalCount: 83, number: 36, name: "Ya-Sin", name_ar: "يس" },
  { totalCount: 182, number: 37, name: "As-Saffat", name_ar: "الصافات" },
  { totalCount: 88, number: 38, name: "Sad", name_ar: "ص" },
  { totalCount: 75, number: 39, name: "Az-Zumar", name_ar: "الزمر" },
  { totalCount: 85, number: 40, name: "Ghafir", name_ar: "غافر" },
  { totalCount: 54, number: 41, name: "Fussilat", name_ar: "فصلت" },
  { totalCount: 53, number: 42, name: "Ash-Shura", name_ar: "الشورى" },
  { totalCount: 89, number: 43, name: "Az-Zukhruf", name_ar: "الزخرف" },
  { totalCount: 59, number: 44, name: "Ad-Dukhan", name_ar: "الدخان" },
  { totalCount: 37, number: 45, name: "Al-Jathiyah", name_ar: "الجاثية" },
  { totalCount: 35, number: 46, name: "Al-Ahqaf", name_ar: "الأحقاف" },
  { totalCount: 38, number: 47, name: "Muhammad", name_ar: "محمد" },
  { totalCount: 29, number: 48, name: "Al-Fath", name_ar: "الفتح" },
  { totalCount: 18, number: 49, name: "Al-Hujurat", name_ar: "الحجرات" },
  { totalCount: 45, number: 50, name: "Qaf", name_ar: "ق" },
  { totalCount: 60, number: 51, name: "Adh-Dhariyat", name_ar: "الذاريات" },
  { totalCount: 49, number: 52, name: "At-Tur", name_ar: "الطور" },
  { totalCount: 62, number: 53, name: "An-Najm", name_ar: "النجم" },
  { totalCount: 55, number: 54, name: "Al-Qamar", name_ar: "القمر" },
  { totalCount: 78, number: 55, name: "Ar-Rahman", name_ar: "الرحمن" },
  { totalCount: 96, number: 56, name: "Al-Waqi'ah", name_ar: "الواقعة" },
  { totalCount: 29, number: 57, name: "Al-Hadid", name_ar: "الحديد" },
  { totalCount: 22, number: 58, name: "Al-Mujadila", name_ar: "المجادلة" },
  { totalCount: 24, number: 59, name: "Al-Hashr", name_ar: "الحشر" },
  { totalCount: 13, number: 60, name: "Al-Mumtahanah", name_ar: "الممتحنة" },
  { totalCount: 14, number: 61, name: "As-Saff", name_ar: "الصف" },
  { totalCount: 11, number: 62, name: "Al-Jum'ah", name_ar: "الجمعة" },
  { totalCount: 11, number: 63, name: "Al-Munafiqun", name_ar: "المنافقون" },
  { totalCount: 18, number: 64, name: "At-Taghabun", name_ar: "التغابن" },
  { totalCount: 12, number: 65, name: "At-Talaq", name_ar: "الطلاق" },
  { totalCount: 12, number: 66, name: "At-Tahrim", name_ar: "التحريم" },
  { totalCount: 30, number: 67, name: "Al-Mulk", name_ar: "الملك" },
  { totalCount: 52, number: 68, name: "Al-Qalam", name_ar: "القلم" },
  { totalCount: 52, number: 69, name: "Al-Haqqah", name_ar: "الحاقة" },
  { totalCount: 44, number: 70, name: "Al-Ma'arij", name_ar: "المعارج" },
  { totalCount: 28, number: 71, name: "Nuh", name_ar: "نوح" },
  { totalCount: 28, number: 72, name: "Al-Jinn", name_ar: "الجن" },
  { totalCount: 20, number: 73, name: "Al-Muzzammil", name_ar: "المزمل" },
  { totalCount: 56, number: 74, name: "Al-Muddathir", name_ar: "المدثر" },
  { totalCount: 40, number: 75, name: "Al-Qiyamah", name_ar: "القيامة" },
  { totalCount: 31, number: 76, name: "Al-Insan", name_ar: "الإنسان" },
  { totalCount: 50, number: 77, name: "Al-Mursalat", name_ar: "المرسلات" },
  { totalCount: 40, number: 78, name: "An-Naba", name_ar: "النبأ" },
  { totalCount: 46, number: 79, name: "An-Nazi'at", name_ar: "النازعات" },
  { totalCount: 42, number: 80, name: "Abasa", name_ar: "عبس" },
  { totalCount: 29, number: 81, name: "At-Takwir", name_ar: "التكوير" },
  { totalCount: 19, number: 82, name: "Al-Infitar", name_ar: "الإنفطار" },
  { totalCount: 36, number: 83, name: "Al-Mutaffifin", name_ar: "المطففين" },
  { totalCount: 25, number: 84, name: "Al-Inshiqaq", name_ar: "الإنشقاق" },
  { totalCount: 22, number: 85, name: "Al-Buruj", name_ar: "البروج" },
  { totalCount: 17, number: 86, name: "At-Tariq", name_ar: "الطارق" },
  { totalCount: 19, number: 87, name: "Al-A'la", name_ar: "الأعلى" },
  { totalCount: 26, number: 88, name: "Al-Ghashiyah", name_ar: "الغاشية" },
  { totalCount: 30, number: 89, name: "Al-Fajr", name_ar: "الفجر" },
  { totalCount: 20, number: 90, name: "Al-Balad", name_ar: "البلد" },
  { totalCount: 15, number: 91, name: "Ash-Shams", name_ar: "الشمس" },
  { totalCount: 21, number: 92, name: "Al-Lail", name_ar: "الليل" },
  { totalCount: 11, number: 93, name: "Ad-Duha", name_ar: "الضحى" },
  { totalCount: 8, number: 94, name: "Ash-Sharh", name_ar: "الشرح" },
  { totalCount: 8, number: 95, name: "At-Tin", name_ar: "التين" },
  { totalCount: 19, number: 96, name: "Al-Alaq", name_ar: "العلق" },
  { totalCount: 5, number: 97, name: "Al-Qadr", name_ar: "القدر" },
  { totalCount: 8, number: 98, name: "Al-Bayyina", name_ar: "البينة" },
  { totalCount: 8, number: 99, name: "Az-Zalzalah", name_ar: "الزلزلة" },
  { totalCount: 11, number: 100, name: "Al-Adiyat", name_ar: "العاديات" },
  { totalCount: 11, number: 101, name: "Al-Qari'ah", name_ar: "القارعة" },
  { totalCount: 8, number: 102, name: "At-Takathur", name_ar: "التكاثر" },
  { totalCount: 3, number: 103, name: "Al-Asr", name_ar: "العصر" },
  { totalCount: 9, number: 104, name: "Al-Humazah", name_ar: "الهمزة" },
  { totalCount: 5, number: 105, name: "Al-Fil", name_ar: "الفيل" },
  { totalCount: 4, number: 106, name: "Quraysh", name_ar: "قريش" },
  { totalCount: 7, number: 107, name: "Al-Ma'un", name_ar: "الماعون" },
  { totalCount: 3, number: 108, name: "Al-Kawthar", name_ar: "الكوثر" },
  { totalCount: 6, number: 109, name: "Al-Kafirun", name_ar: "الكافرون" },
  { totalCount: 3, number: 110, name: "An-Nasr", name_ar: "النصر" },
  { totalCount: 5, number: 111, name: "Al-Masad", name_ar: "المسد" },
  { totalCount: 4, number: 112, name: "Al-Ikhlas", name_ar: "الإخلاص" },
  { totalCount: 5, number: 113, name: "Al-Falaq", name_ar: "الفلق" },
  { totalCount: 6, number: 114, name: "An-Nas", name_ar: "الناس" },
];
